/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/services/jdr/auth/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Setup Status */
        get: operations["get_setup_status_services_jdr_auth_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Setup */
        post: operations["post_setup_services_jdr_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Login */
        post: operations["post_login_services_jdr_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auth Me */
        get: operations["get_auth_me_services_jdr_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Logout */
        post: operations["post_logout_services_jdr_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Users */
        get: operations["get_users_services_jdr_users_get"];
        put?: never;
        /** Post User */
        post: operations["post_user_services_jdr_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User Route */
        delete: operations["delete_user_route_services_jdr_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_services_jdr_users__user_id__patch"];
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload the audio of a session and enqueue its transcription. */
        post: operations["post_audio_services_jdr_sessions__session_id__audio_post"];
        /**
         * Purge a session's audio file and reset the session so a new upload can be sent.
         * @description Drop the audio file on disk and reset the session to ``created``.
         *
         *     Use cases (matches data-model.md §3 retry arrow
         *     ``transcription_failed → audio_uploaded`` and the analogous
         *     cancel-before-transcription path):
         *
         *     - The MJ uploaded the wrong file and wants to re-upload before the
         *       worker picks it up.
         *     - Transcription failed and the MJ wants to try again with a different
         *       audio (or after the upstream provider has recovered).
         *
         *     Refused (409) when ``state ∈ {transcribing, transcribed}``: see
         *     ``logic.purge_audio_for_session`` for the rationale.
         */
        delete: operations["delete_audio_services_jdr_sessions__session_id__audio_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/live/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * (stub — Jalon 5) Open a live ingestion session.
         * @description Always raises 501 ``live-not-implemented``.
         *
         *     The Pydantic body is validated first so a malformed payload still
         *     returns 422, keeping the published contract honest even when the
         *     implementation lands later.
         */
        post: operations["post_live_session_services_jdr_live_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the MJ's sessions. */
        get: operations["list_sessions_services_jdr_sessions_get"];
        put?: never;
        /**
         * Create a new JDR session.
         * @description Create a session owned by the authenticated MJ.
         *
         *     The body holds the human title and the date the session actually
         *     took place (``recorded_at``). State starts at ``created``; the
         *     audio is uploaded separately via ``POST /sessions/{id}/audio``.
         *     The optional ``campaign_context`` is a steering block for the LLM
         *     (PNJ récurrents, ton, fil narratif) — see PATCH for updating it.
         */
        post: operations["create_session_services_jdr_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one of the MJ's sessions. */
        get: operations["get_session_services_jdr_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Partially update a session (title and/or campaign_context).
         * @description Apply a partial update.
         *
         *     Only the fields present in the body are touched. To clear
         *     ``campaign_context``, send ``{"campaign_context": null}`` explicitly —
         *     omitting the key leaves the existing value alone. Updating
         *     ``campaign_context`` does NOT re-run any previously generated
         *     artefact; the new value affects only future generations.
         *
         *     ``transcription_mode`` is immutable after creation (FR-002 of
         *     feature 002): any PATCH body referencing it is rejected with 422.
         */
        patch: operations["patch_session_services_jdr_sessions__session_id__patch"];
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chunked transcription of a non_diarised session (ordered).
         * @description Return the chunks (text, ordre) of a non_diarised session.
         *
         *     Reserved for non_diarised sessions — diarised sessions use the
         *     `GET /transcription` endpoint instead (409 wrong-mode otherwise).
         *     Returns 404 transcription-not-ready if no chunks have been produced
         *     yet for the session.
         */
        get: operations["get_session_chunks_services_jdr_sessions__session_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/pjs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current MJ's PJs. */
        get: operations["list_pjs_services_jdr_pjs_get"];
        put?: never;
        /**
         * Create a PJ (player-character) owned by the current MJ.
         * @description A PJ is stable across sessions — it's the narrative anchor that
         *     later gets mapped to a diarisation ``speaker_label`` per session
         *     (sub-lot 5b) and to a player API key (US4).
         *
         *     Duplicate name within the same MJ -> 409 ``duplicate-pj``.
         */
        post: operations["create_pj_services_jdr_pjs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the current speaker→PJ mapping for a session.
         * @description Returns 200 with an empty dict when the session has no mapping
         *     yet (resource exists but is not configured).
         *
         *     409 wrong-mode if the session is non_diarised (use GET /players).
         */
        get: operations["get_session_mapping_services_jdr_sessions__session_id__mapping_get"];
        /**
         * Replace the speaker→PJ mapping for a session.
         * @description Replace the mapping in one atomic write.
         *
         *     - 404 if the session does not belong to the current MJ.
         *     - 409 wrong-mode if the session is non_diarised (use /players instead).
         *     - 409 if the session is not yet in ``state=transcribed``.
         *     - 422 if any ``pj_id`` is unknown or owned by another MJ.
         *
         *     Side-effect: any existing ``pov:*`` artefact for this session is
         *     deleted (data-model.md §6 invariant). A subsequent
         *     ``POST /artifacts/povs`` is required to regenerate them.
         */
        put: operations["put_session_mapping_services_jdr_sessions__session_id__mapping_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current PJ list of a non_diarised session. */
        get: operations["get_session_players_services_jdr_sessions__session_id__players_get"];
        put?: never;
        /**
         * Replace the list of PJ present at a non_diarised session.
         * @description Declare the PJ present at a non_diarised session (FR-012).
         *
         *     PUT-like semantics — the provided list replaces the previous one
         *     integrally. Each ``pj_id`` must belong to the current MJ (422
         *     ``invalid-player-list`` otherwise). Reserved for non_diarised
         *     sessions (409 ``wrong-mode`` on diarised).
         */
        post: operations["post_session_players_services_jdr_sessions__session_id__players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/transcription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the diarised transcription of a session. */
        get: operations["get_transcription_services_jdr_sessions__session_id__transcription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/transcription.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the transcription as Markdown (text/markdown). */
        get: operations["get_transcription_md_services_jdr_sessions__session_id__transcription_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/artifacts/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the narrative summary of a session. */
        get: operations["get_narrative_services_jdr_sessions__session_id__artifacts_narrative_get"];
        put?: never;
        /** Trigger the narrative summary generation for a session. */
        post: operations["post_narrative_services_jdr_sessions__session_id__artifacts_narrative_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/artifacts/narrative.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the narrative summary as Markdown (text/markdown). */
        get: operations["get_narrative_md_services_jdr_sessions__session_id__artifacts_narrative_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/artifacts/elements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the structured-elements card of a session. */
        get: operations["get_elements_services_jdr_sessions__session_id__artifacts_elements_get"];
        put?: never;
        /** Trigger the structured-elements card generation for a session. */
        post: operations["post_elements_services_jdr_sessions__session_id__artifacts_elements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/artifacts/elements.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the structured-elements card as Markdown (text/markdown). */
        get: operations["get_elements_md_services_jdr_sessions__session_id__artifacts_elements_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/artifacts/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the global session summary (JSON). */
        get: operations["get_summary_services_jdr_sessions__session_id__artifacts_summary_get"];
        put?: never;
        /**
         * Trigger the global session summary (map-reduce LLM).
         * @description Enqueue the map-reduce summary job for a non_diarised session.
         *
         *     Pre-conditions:
         *     - session must belong to the MJ (404 otherwise)
         *     - session must be in non_diarised mode (409 wrong-mode)
         *     - session must be in state=transcribed (409 session-not-transcribed)
         *     - session must have at least 1 chunk (409 no-chunks)
         *
         *     Side effect documented under FR-011: each new summary job resets
         *     chunks.summary_text and cascade-deletes existing narrative /
         *     elements / pov:* artefacts for the session. The atomicity is
         *     enforced by ``_generate_summary`` (see research.md §2).
         */
        post: operations["post_summary_services_jdr_sessions__session_id__artifacts_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/artifacts/summary.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the global session summary as Markdown (text/markdown). */
        get: operations["get_summary_md_services_jdr_sessions__session_id__artifacts_summary_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/artifacts/povs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger POV generation — one artefact per mapped PJ.
         * @description Enqueue a single job that generates one ``pov:<pj_id>`` artefact
         *     per row in the session's mapping. Pre-conditions match the other
         *     generators (404 if foreign, 409 if not transcribed) plus FR-011:
         *     a 409 ``no-mapping`` is raised when the session has no configured
         *     speaker-PJ mapping yet — the operator must call
         *     ``PUT /mapping`` first.
         */
        post: operations["post_povs_services_jdr_sessions__session_id__artifacts_povs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/sessions/{session_id}/artifacts/povs/{pj_id_str}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one PJ's POV — JSON, or Markdown via the .md suffix.
         * @description One route handles both representations because the ``.md`` suffix
         *     pattern would otherwise collide with the UUID path param at the
         *     Starlette routing layer (``{pj_id}`` matches ``[^/]+`` which greedily
         *     swallows the ``.md``).
         *
         *     - ``GET .../povs/<uuid>``     → JSON (:class:`PovArtifactOut`)
         *     - ``GET .../povs/<uuid>.md``  → Markdown (``text/markdown``)
         */
        get: operations["get_pov_services_jdr_sessions__session_id__artifacts_povs__pj_id_str__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll a player and return the plaintext Bearer token (once).
         * @description Create a player key bound to one of the GM's PJs.
         *
         *     The plaintext token is returned exactly once — store it now, the
         *     server only keeps the Argon2 hash.
         */
        post: operations["post_player_services_jdr_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a player key (immediate effect on the next request). */
        delete: operations["delete_player_services_jdr_players__player_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile of the current player (name + their PJ). */
        get: operations["get_me_services_jdr_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the sessions where the current player's PJ is mapped. */
        get: operations["get_my_sessions_services_jdr_me_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/me/sessions/{session_id}/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the global narrative summary of a session (player view). */
        get: operations["get_my_narrative_services_jdr_me_sessions__session_id__narrative_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/me/sessions/{session_id}/narrative.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the global narrative summary as Markdown (player view). */
        get: operations["get_my_narrative_md_services_jdr_me_sessions__session_id__narrative_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/me/sessions/{session_id}/pov": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current player's POV summary for a session. */
        get: operations["get_my_pov_services_jdr_me_sessions__session_id__pov_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/me/sessions/{session_id}/pov.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the current player's POV as Markdown. */
        get: operations["get_my_pov_md_services_jdr_me_sessions__session_id__pov_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/jdr/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the status of a JDR-service async job.
         * @description Project an RQ job into the project's JobOut shape.
         *
         *     RQ holds the live state for 24h on success / 7d on failure. Cross-
         *     tenant access (a GM polling another GM's job) returns 404 so the
         *     endpoint never confirms the existence of a foreign job.
         */
        get: operations["get_job_services_jdr_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness alias (legacy Jalon 0).
         * @description Legacy liveness endpoint kept for backward compatibility.
         *
         *     Equivalent to ``/healthz``. New monitoring setups should target
         *     ``/healthz`` (liveness) and ``/readyz`` (readiness) instead.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe (Jalon 6).
         * @description Always 200 as long as the Python process is alive.
         *
         *     Does NOT check external dependencies. Use ``/readyz`` to decide
         *     whether to send traffic. Intent: orchestrator should restart the
         *     process iff this fails.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe — DB + Redis (Jalon 6).
         * @description 200 if every backing dependency is reachable, 503 otherwise.
         *
         *     Per-check status surfaced in the body so an operator can see
         *     which dependency is down without parsing logs.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AudioUploadOut
         * @description Response of ``POST /sessions/{id}/audio``.
         */
        AudioUploadOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Path
             * @description Path on disk relative to KAEYRIS_DATA_DIR.
             */
            path: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Duration Seconds
             * @description Audio duration in seconds. ``null`` when ``ffprobe`` is unavailable on the host — non-fatal.
             */
            duration_seconds?: number | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /**
             * Job Id
             * @description RQ job identifier for the queued transcription.
             */
            job_id: string;
        };
        /** AuthMeCampaignOut */
        AuthMeCampaignOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Character Id */
            character_id?: string | null;
        };
        /** AuthMeOut */
        AuthMeOut: {
            user: components["schemas"]["AuthMeUserOut"];
            active_campaign: components["schemas"]["AuthMeCampaignOut"] | null;
        };
        /** AuthMeUserOut */
        AuthMeUserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
        };
        /** Body_post_audio_services_jdr_sessions__session_id__audio_post */
        Body_post_audio_services_jdr_sessions__session_id__audio_post: {
            /**
             * Audio
             * @description Audio file (M4A). The upload itself is streamed to disk and has no hard size limit at this layer. Note: with TRANSCRIPTION_PROVIDER=cloud, the OpenAI Whisper API caps individual requests at 25 MB, so the transcription job has to chunk larger files (R3 — to be implemented). With provider=local (LAN GPU host running faster-whisper), any size is supported.
             */
            audio: string;
        };
        /**
         * ChunkListOut
         * @description Response of `GET /services/jdr/sessions/{session_id}/chunks`.
         */
        ChunkListOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Items */
            items: components["schemas"]["ChunkOut"][];
        };
        /**
         * ChunkOut
         * @description One row of `jdr_chunks` as exposed by `GET /sessions/{id}/chunks`.
         *
         *     `summary_text` is intentionally NOT exposed — it is internal to the
         *     LLM pipeline (research.md §5).
         */
        ChunkOut: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Ordre */
            ordre: number;
            /** Text */
            text: string;
        };
        /**
         * Element
         * @description One row of the four-category elements card.
         *
         *     The LLM may return arbitrary keys; we surface only ``name`` and
         *     ``description`` so the public contract is stable across model swaps.
         */
        Element: {
            /**
             * Name
             * @description Short label (proper name or descriptor).
             */
            name: string;
            /**
             * Description
             * @description One-sentence description (≤ ~25 words).
             * @default
             */
            description: string;
        };
        /**
         * ElementsArtifactOut
         * @description Public projection of an ``Artifact(kind='elements')`` row.
         *
         *     The four lists are *always* present, even when empty (``[]``). See
         *     acceptance scenario US 2.3 in ``spec.md``.
         */
        ElementsArtifactOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Npcs */
            npcs?: components["schemas"]["Element"][];
            /** Locations */
            locations?: components["schemas"]["Element"][];
            /** Items */
            items?: components["schemas"]["Element"][];
            /** Clues */
            clues?: components["schemas"]["Element"][];
            /** Model Used */
            model_used: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "transcription" | "narrative" | "elements" | "povs" | "summary";
        /**
         * JobOut
         * @description Job status projection — see ``data-model.md`` §8.
         */
        JobOut: {
            /**
             * Id
             * @description RQ job identifier (echoed from the queue).
             */
            id: string;
            kind: components["schemas"]["JobKind"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["JobStatus"];
            /** Failure Reason */
            failure_reason?: string | null;
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
        };
        /**
         * JobQueuedOut
         * @description Reply to an artefact-trigger POST: a freshly enqueued RQ job.
         *
         *     Status starts at ``queued``; the worker updates it as it processes.
         *     The full lifecycle (running -> succeeded/failed) is observable via
         *     GET /jobs/{id} (added in sub-lot 3f).
         */
        JobQueuedOut: {
            /**
             * Id
             * @description RQ job identifier.
             */
            id: string;
            kind: components["schemas"]["JobKind"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * @description Initial status after enqueue.
             * @default queued
             */
            status: components["schemas"]["JobStatus"];
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /**
         * LiveSessionInit
         * @description Body that the future ``POST /live/sessions`` will accept.
         *
         *     Published as a Pydantic model so the OpenAPI schema is complete even
         *     though the handler always raises 501.
         */
        LiveSessionInit: {
            /**
             * Title
             * @description Human-readable title for the live session.
             */
            title: string;
            /**
             * Campaign Context
             * @description Optional campaign-bible block (same semantics as batch mode).
             */
            campaign_context?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Profile */
            profile: string;
            /** Password */
            password: string;
        };
        /**
         * MappingOut
         * @description Response for both PUT and GET ``/mapping``.
         *
         *     ``updated_at`` is the most recent ``updated_at`` across the rows,
         *     or ``None`` when the session has no mapping yet.
         */
        MappingOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * MappingPut
         * @description Body for ``PUT /services/jdr/sessions/{session_id}/mapping``.
         *
         *     Shape ``{speaker_label: pj_id}`` per ``contracts/rest-api.md``
         *     §148-163.
         */
        MappingPut: {
            /**
             * Mapping
             * @description speaker_label -> pj_id
             */
            mapping?: {
                [key: string]: string;
            };
        };
        /**
         * MeOut
         * @description Response of ``GET /services/jdr/me``.
         */
        MeOut: {
            /** Name */
            name: string;
            pj: components["schemas"]["PjMini"];
        };
        /**
         * NarrativeArtifactOut
         * @description Public projection of an ``Artifact(kind='narrative')`` row.
         */
        NarrativeArtifactOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Text
             * @description French narrative summary produced by the LLM.
             */
            text: string;
            /** Model Used */
            model_used: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** Page[PjOut] */
        Page_PjOut_: {
            /** Items */
            items: components["schemas"]["PjOut"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Size
             * @default 50
             */
            size: number;
        };
        /** Page[SessionOut] */
        Page_SessionOut_: {
            /** Items */
            items: components["schemas"]["SessionOut"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Size
             * @default 50
             */
            size: number;
        };
        /**
         * PjCreate
         * @description Payload accepted by ``POST /services/jdr/pjs``.
         */
        PjCreate: {
            /** Name */
            name: string;
        };
        /**
         * PjMini
         * @description Compact PJ projection used inside ``MeOut``.
         */
        PjMini: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * PjOut
         * @description Public projection of ``jdr_pjs`` rows.
         */
        PjOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PlayerCreate
         * @description Body for ``POST /services/jdr/players``.
         */
        PlayerCreate: {
            /** Name */
            name: string;
            /**
             * Pj Id
             * Format: uuid
             */
            pj_id: string;
        };
        /**
         * PlayerOut
         * @description Response of ``POST /services/jdr/players``.
         *
         *     ``token`` is the *plaintext* Bearer token; it is returned **once** at
         *     creation and never again. The server only stores the Argon2 hash.
         */
        PlayerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Pj Id
             * Format: uuid
             */
            pj_id: string;
            /**
             * Token
             * @description Plaintext Bearer token. Shown only on this 201 response. Store it now — the server only keeps an Argon2 hash.
             */
            token: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PlayerSessionItem
         * @description One row of ``GET /services/jdr/me/sessions``.
         */
        PlayerSessionItem: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Title */
            title: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /**
         * PlayerSessionListOut
         * @description Envelope for ``GET /services/jdr/me/sessions``.
         */
        PlayerSessionListOut: {
            /** Items */
            items: components["schemas"]["PlayerSessionItem"][];
        };
        /**
         * PovArtifactOut
         * @description Public projection of an ``Artifact(kind='pov:<pj_id>')`` row.
         *
         *     ``pj_id`` is exposed at the top level for clients that don't want to
         *     parse the composite ``kind`` field.
         */
        PovArtifactOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Pj Id
             * Format: uuid
             */
            pj_id: string;
            /**
             * Text
             * @description French POV summary scoped to this PJ.
             */
            text: string;
            /** Model Used */
            model_used: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * Profile
         * @enum {string}
         */
        Profile: "gm" | "user";
        /**
         * SessionCreate
         * @description Payload accepted by ``POST /services/jdr/sessions``.
         */
        SessionCreate: {
            /** Title */
            title: string;
            /**
             * Recorded At
             * Format: date-time
             * @description When the session actually took place (not the upload time). ISO-8601 with timezone.
             */
            recorded_at: string;
            /** @description Optional. 'diarised' (default, Jalon 5 behaviour) or 'non_diarised' (chunked transcription + map-reduce LLM summary). Immutable after creation. Default applied server-side if omitted. */
            transcription_mode?: components["schemas"]["TranscriptionMode"] | null;
            /**
             * Campaign Context
             * @description Optional campaign-bible block prepended to every narrative / elements LLM prompt for this session. Use it to anchor the model on recurring PNJ, the campaign tone, or the current story arc. Can be updated later via PATCH.
             */
            campaign_context?: string | null;
        };
        /**
         * SessionMode
         * @enum {string}
         */
        SessionMode: "batch" | "live";
        /**
         * SessionOut
         * @description Public projection of ``jdr_sessions`` rows.
         */
        SessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            mode: components["schemas"]["SessionMode"];
            state: components["schemas"]["SessionState"];
            transcription_mode: components["schemas"]["TranscriptionMode"];
            /** Campaign Context */
            campaign_context?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SessionPlayersIn
         * @description Body of `POST /services/jdr/sessions/{session_id}/players`.
         *
         *     Replaces the player list integrally (PUT-like semantics).
         */
        SessionPlayersIn: {
            /** Pj Ids */
            pj_ids: string[];
        };
        /**
         * SessionPlayersOut
         * @description Response of `POST` and `GET /sessions/{session_id}/players`.
         */
        SessionPlayersOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Pj Ids */
            pj_ids: string[];
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * SessionState
         * @description Lifecycle of a session — see data-model.md §3.
         * @enum {string}
         */
        SessionState: "created" | "audio_uploaded" | "transcribing" | "transcription_failed" | "transcribed";
        /**
         * SessionUpdate
         * @description Payload accepted by ``PATCH /services/jdr/sessions/{id}``.
         *
         *     Every field is optional — the route applies only the keys that are
         *     present (PATCH semantics). To clear ``campaign_context``, send
         *     ``"campaign_context": null`` explicitly (the route distinguishes
         *     "unset" from "explicit null" via Pydantic's ``model_fields_set``).
         */
        SessionUpdate: {
            /** Title */
            title?: string | null;
            /** Campaign Context */
            campaign_context?: string | null;
            transcription_mode?: components["schemas"]["TranscriptionMode"] | null;
            /** Campaign Id */
            campaign_id?: string | null;
        };
        /** SetupRequest */
        SetupRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** SetupStatusOut */
        SetupStatusOut: {
            /** Required */
            required: boolean;
        };
        /**
         * SummaryArtifactOut
         * @description Public projection of an ``Artifact(kind='summary')`` row.
         */
        SummaryArtifactOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Text
             * @description Global session summary in French.
             */
            text: string;
            /** Model Used */
            model_used: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * TranscriptionMode
         * @description Per-session transcription posture — see feature 002 data-model.md §2.
         *
         *     - ``DIARISED`` (default): Jalon 5 pipeline, segments stored in
         *       ``jdr_transcriptions`` with speaker labels.
         *     - ``NON_DIARISED``: chunked transcription stored in ``jdr_chunks``,
         *       no speaker labels, downstream artefacts consume per-chunk summaries.
         * @enum {string}
         */
        TranscriptionMode: "diarised" | "non_diarised";
        /**
         * TranscriptionOut
         * @description Public projection of ``jdr_transcriptions`` rows.
         */
        TranscriptionOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Segments */
            segments: components["schemas"]["TranscriptionSegmentOut"][];
            /**
             * Language
             * @description BCP-47 code, e.g. 'fr'.
             */
            language: string;
            /** Model Used */
            model_used: string;
            /**
             * Provider
             * @description 'cloud' | 'local' | 'mock'.
             */
            provider: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /**
         * TranscriptionSegmentOut
         * @description One diarised utterance in a transcription.
         */
        TranscriptionSegmentOut: {
            /**
             * Speaker Label
             * @description Raw label produced by the backend ('speaker_1', 'unknown', …). The mapping to PJs is a per-session business decision exposed via /mapping (US3).
             */
            speaker_label: string;
            /** Start Seconds */
            start_seconds: number;
            /** End Seconds */
            end_seconds: number;
            /** Text */
            text: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            profile: components["schemas"]["Profile"];
            /** Password */
            password: string;
        };
        /** UserListOut */
        UserListOut: {
            /** Items */
            items: components["schemas"]["UserOut"][];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            profile: components["schemas"]["Profile"];
            status: components["schemas"]["UserStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Login At */
            last_login_at?: string | null;
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "active" | "inactive" | "deleted";
        /** UserUpdate */
        UserUpdate: {
            profile?: components["schemas"]["Profile"] | null;
            /** Password */
            password?: string | null;
            status?: components["schemas"]["UserStatus"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_setup_status_services_jdr_auth_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
    post_setup_services_jdr_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_login_services_jdr_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auth_me_services_jdr_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeOut"];
                };
            };
        };
    };
    post_logout_services_jdr_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_users_services_jdr_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"];
                };
            };
        };
    };
    post_user_services_jdr_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_route_services_jdr_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_services_jdr_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_audio_services_jdr_sessions__session_id__audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_audio_services_jdr_sessions__session_id__audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_audio_services_jdr_sessions__session_id__audio_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_live_session_services_jdr_live_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveSessionInit"];
            };
        };
        responses: {
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Successful Response */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_sessions_services_jdr_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SessionOut_"];
                };
            };
        };
    };
    create_session_services_jdr_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_services_jdr_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_session_services_jdr_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_chunks_services_jdr_sessions__session_id__chunks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pjs_services_jdr_pjs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PjOut_"];
                };
            };
        };
    };
    create_pj_services_jdr_pjs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PjCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PjOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_mapping_services_jdr_sessions__session_id__mapping_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_session_mapping_services_jdr_sessions__session_id__mapping_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_players_services_jdr_sessions__session_id__players_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPlayersOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_session_players_services_jdr_sessions__session_id__players_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionPlayersIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPlayersOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcription_services_jdr_sessions__session_id__transcription_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcription_md_services_jdr_sessions__session_id__transcription_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_narrative_services_jdr_sessions__session_id__artifacts_narrative_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeArtifactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_narrative_services_jdr_sessions__session_id__artifacts_narrative_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobQueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_narrative_md_services_jdr_sessions__session_id__artifacts_narrative_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_elements_services_jdr_sessions__session_id__artifacts_elements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementsArtifactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_elements_services_jdr_sessions__session_id__artifacts_elements_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobQueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_elements_md_services_jdr_sessions__session_id__artifacts_elements_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_services_jdr_sessions__session_id__artifacts_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryArtifactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_summary_services_jdr_sessions__session_id__artifacts_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobQueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_md_services_jdr_sessions__session_id__artifacts_summary_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_povs_services_jdr_sessions__session_id__artifacts_povs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobQueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pov_services_jdr_sessions__session_id__artifacts_povs__pj_id_str__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                pj_id_str: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_player_services_jdr_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_player_services_jdr_players__player_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_services_jdr_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    get_my_sessions_services_jdr_me_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSessionListOut"];
                };
            };
        };
    };
    get_my_narrative_services_jdr_me_sessions__session_id__narrative_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeArtifactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_narrative_md_services_jdr_me_sessions__session_id__narrative_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_pov_services_jdr_me_sessions__session_id__pov_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PovArtifactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_pov_md_services_jdr_me_sessions__session_id__pov_md_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_services_jdr_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
